dist: trusty

language: rust

branches:
    except:
        - /^wip\/.*/

script:
  - cargo build --verbose
  - cargo test --verbose

addons:
  apt:
    packages:
      - libdbus-1-dev
      - libudev-dev
